In [1]:
library(tidyverse)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
rnas <- read_tsv("mRNA-422336955/featurecounts/megamatrix.tsv")
head(rnas)

Rows: 48440 Columns: 13
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): Geneid
dbl (12): Diff_mock_1, Diff_mock_2, Diff_mock_3, mesc_aux_1, mesc_aux_2, mes...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  Geneid               Diff_mock_1 Diff_mock_2 Diff_mock_3 mesc_aux_1
1 ENSMUSG00000102693.1 0           0            0           0
2 ENSMUSG00000064842.1 0           0            0           0
3 ENSMUSG00000051951.5 6           2           12          14
4 ENSMUSG00000102851.1 0           0            0           0
5 ENSMUSG00000103377.1 0           0            0           0
6 ENSMUSG00000104017.1 0           0            0           0
  mesc_aux_2 mesc_aux_3 mesc_mock_1 mesc_mock_2 mesc_mock_3 mesc_res_1
1  0          0         0           0           0            0
2  0          0         0           0           0            0
3 14         12         5           0           0           15
4  0          0         0           0           0            0
5  0          0         0           0           0            0
6  0          0         0           0           0            1
  mesc_res_2 mesc_res_3
1  0          0
2  0          0
3 11         18
4  0          0
5  0          0
6  0          0

In [6]:
bp <- read_csv("UltimaListaPENDIENTES/5_Boxplot_counteos//NucleacionBP-deseq.csv")
head(bp)
cntrl <- read_csv("UltimaListaPENDIENTES//5_Boxplot_counteos/ControlExclusive.csv")
head(cntrl)

Rows: 1099 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): geneId

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  geneId
1 ENSMUSG00000000093.6
2 ENSMUSG00000000093.6
3 ENSMUSG00000000094.12
4 ENSMUSG00000000247.11
5 ENSMUSG00000000247.11
6 ENSMUSG00000000247.11

Rows: 4608 Columns: 1
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): geneId

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  geneId
1 ENSMUSG00000000049.11
2 ENSMUSG00000000058.6
3 ENSMUSG00000000094.12
4 ENSMUSG00000000094.12
5 ENSMUSG00000000120.6
6 ENSMUSG00000000120.6

In [13]:
table(bp$geneId %in% cntrl$geneId)
table(cntrl$geneId %in% bp$geneId)

FALSE  TRUE
  858   241

FALSE  TRUE
 4349   259

In [18]:
bpr <- bp$geneId[bp$geneId %in% cntrl$geneId]
cnr <- cntrl$geneId[cntrl$geneId %in% bp$geneId]
write(bpr,"bpr.txt")
write (cnr,"cnr.txt")